### ISSUE TITLE
Add Dockerfile validation with Hadolint

### ISSUE THREAD

**Issue by bgauduch** [Zenika/terraform-azure-cli#14]
Need to setup a CI first (CircleCI ? Travis ? Codeship ?)
run Dockerfile against Hadolint before build

**Comment by pyaillet** [comment]
See #27 

Do you think travis should also push to the docker hub ?

**Comment by bgauduch** [comment]
I believe the image should not be pushed if hadolint fail.
I do not know how the docker Hub behave if a CI fail on a branch, gotta check this out !

If the hub is smart enought not to push the image on CI failure, I believe there is no need to put this step in the Travis CI 😉

**Comment by bgauduch** [comment]
After a quick check, it seems possible to use the Docker Hub [automated test feature](https://docs.docker.com/docker-hub/builds/automated-testing/)
 
But for a matter of consistency, I believe all CI actions should take place at the same place, so in our case travis should handle the test, build and push actions.

@pyaillet WDYT ?

**Comment by pyaillet** [comment]
Closed by #32
