### ISSUE TITLE
 Update image tagging strategy and CI to display both Azure and Terraform CLI version

### ISSUE THREAD

**Issue by bgauduch** [Zenika/terraform-azure-cli#16]
Instead of using arbitrary tag numbers like `2.3`, it might be better to implement a real tagging strategy to display toolling version like so:
```
r1.2-tf0.12.9-azcli2.0.74
```
with:
* `r`= release tag version
* `tf` = Terraform CLI version
* `azcli`= Azure CLI version

**Comment by pyaillet** [comment]
This one is related to #46 I think.

How should we specify the supported `terraform` and `az` versions ?

**Comment by bgauduch** [comment]
I believe it should be some env vars with a list of desired version, set up before calling a build script looping on it and producing all the images. It should be parralelized though, and will impact the current CI structure.

The final implementation is not clear for the moment, so the subject is open for suggestions 😉

**Comment by bgauduch** [comment]
I will implement this using Github action strategy.
closing duplicated #46.
