### ISSUE TITLE
Git is not installed thus it's not possible to reference a module with a Git URL

### ISSUE THREAD

**Issue by rouxton** [Zenika/terraform-azure-cli#24]
We have a comprehensive set of modules availables though our GitLab repos and we are referencong them in TF with the syntax source = "git::https://urlofmymodulerepo"
It seems the image does not include the Git package thus breaking this feature. 
I think it's important to make it part of the standard image by default (we can of course build a custom image) as Terraform relies on it.

Thanks

**Comment by bgauduch** [comment]
Hello @rouxton, thanks a lot for the feedback an opening an issue !

Git seems indeed unavoidable in your use case and more globally for anyone relying on TF modules via git.

I believe it should indeed be added in the build stage, feel free to open a PR if I don't have the time to add this today 😉

**Comment by bgauduch** [comment]
@rouxton Could you please review the PR #37 ?
