### ISSUE TITLE
Updated Azure CLI = 2.0.80

### ISSUE THREAD

**Issue by ybelMekk** [Zenika/terraform-azure-cli#55]
Is it possible to update cli version to 2.0.80
Im looking to use: az apim backup
It haves some issues in earlier versions.
Now they added som arguments, but when i apply them i get this:

**ERROR: az: error: unrecognized arguments: --backup-name a-name --storage-account-name a-storage --storage-account-container backup --storage-account-key *****

I tried it local with 2.0.80 and it is supported in the latest version.

**Comment by bgauduch** [comment]
Hey @ybelMekk, thanks a lot for crontributing by opening this issue !
Do not hesitate to push a PR with the proper correction if by any chance you feel happy to contribute more 😉 

In the meantime, you can still build the image with desired azure CLI & Terraform versions as described [in the documentation](https://github.com/Zenika/terraform-azure-cli/#build-the-image)

**Comment by ybelMekk** [comment]
Hello! And  thanks for response. Yeah a PR could be a good idea. I use this with github actions and I could not find a option for : docker build in the cointainer options at github actions, only docker create options. So I was not able to set the version my self. Could it be possible to add env. That the cointainer can snap up then using it, like say with G.A? Thanks again. Y

**Comment by bgauduch** [comment]
Hello @ybelMekk , I've merged the version update so you should be able to use `az apim backup` now!

I suggest that you open a new issue to discuss the addition of environment variables 😉
