### ISSUE TITLE
Azure CLI Not Found (az: command not found)

### ISSUE THREAD

**Issue by ahernandez411** [Zenika/terraform-azure-cli#57]
I have a concourse build that runs every 4 hours and uses Azure CLI commands. On Friday April 17th at 10am the build ran successfully. However starting at 2pm the image no longer contains Azure CLI.

In my concourse build I display versions of products for informational purposes. When attempting to get the version number and when attempting to use the cli tool I received command not found.

Here are examples from the build:

Command to be run... 'az --version'
/bin/bash: az: command not found

Run az login for service-account...
/bin/bash: az: command not found

I am not sure what has happened, but the website says a change went in 3 days ago. I would like to use the image before this change but all the metadata states nothing has changed in 7 months.

**Comment by daniel-simpson** [comment]
I'm also having the same issue when trying to use this image.  Looks like something has changed in the base image, as I'm unable to build locally either:

![image](https://user-images.githubusercontent.com/55378310/79939598-de750200-84a2-11ea-97b6-cc11a00cfc6e.png)

**Comment by daniel-simpson** [comment]
I found that I could get a local build running by removing the version restriction on `curl` though, so I'm able to continue for now.  Hopefully this helps anyone blocked for now!

https://github.com/Zenika/terraform-azure-cli/blob/master/Dockerfile#L10
```
-RUN apt-get install -y curl=7.64.0-4
+RUN apt-get install -y curl
```

**Comment by ybelMekk** [comment]
Im also getting the error, no changes..

**Comment by ybelMekk** [comment]
Someone getting in to this soon?

**Comment by daniel-simpson** [comment]
Hopefully this helps ^^ 🙏

**Comment by bgauduch** [comment]
@ahernandez411, @daniel-simpson ,@ybelMekk, sorry to all of you guys, the notification got hidden in the crazy flow of my current GitHub organization....

Thanks to all of you for the report, investigation and @daniel-simpson for the PR 👍 

Looking at it right now and will merge as soon as possible !

**Comment by bgauduch** [comment]
@ahernandez411 , @daniel-simpson ,@ybelMekk => image with tag latest should be ok once the build is done !

To avoid such error in your Ci workflow, you might want to pin a specific release tag for idempotence. This way you can use this image as base for your custom images, or run it directly 😉

**Comment by ybelMekk** [comment]
Yes ur right. But Debian release is 3.0, not using latest azure ver or terraform.

**Comment by bgauduch** [comment]
@ybelMekk your are right, I'm way behind on the release management for this repo.

Actually I'm planning on updating the tag strategy to display the CLI versions. This way each image tag will clearly show what's included, and it should be easier to use ! There is some work to do on the CI workflow though.

**Comment by bgauduch** [comment]
@ybelMekk I've updated the image tag strategy, it will now display the following informations:
* the release tag
* the included tf version
* the included az cli version
Please refer to the readme for more details.

I hope it will make it easier for you guys to follow the image release cycle !
CC @daniel-simpson @ahernandez411

**Comment by ybelMekk** [comment]
Amazing! Thanks for quick response and good work! @bgauduch

**Comment by bgauduch** [comment]
You are welcome @ybelMekk, it was more than needed to allow proper use in your workflow 😉
